apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: microservices
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: microservices
        tier: frontend
    spec:
      containers:
        - name: server
          image: sanjanivicky/karsajobs-ui:lattest
          ports:
            - containerPort: 8000
          env:
            - name: VUE_APP_BACKEND
              value: http://192.168.49.2:30001
