apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: data
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-pv-volume
              mountPath: /data/db
            - name: mongo-configmap
              mountPath: /config
            - name: mongo-secret
              mountPath: /etc/mongo-credentials
      volumes:
        - name: mongo-pv-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-configmap
          configMap:
            name: mongo-configmap
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-secret
          secret:
            secretName: mongo-secret
